# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be66177d1e93922f71280d12719d9109c8f519fa4666fa2c62b11fd0fbee3fdc398e499617f85ca1f9f32abaf444e5dfdc86793fc3839737990beeddc69430c1

test:
  secret_key_base: 817166bf7fdaba9f961abbf047ab9b6589dcda3b04d7145820ffa2fd25731296927147b4433713b8a5b9ea07cdc44952f04683e67448e7af7f55da2fa84f6ece

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
